"""Added cascade code

Revision ID: 1631b784b66c
Revises: 3c836115c178
Create Date: 2024-07-21 20:01:43.858669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1631b784b66c'
down_revision = '3c836115c178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cart', schema=None) as batch_op:
        batch_op.drop_constraint('Cart_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Cart_Product', schema=None) as batch_op:
        batch_op.drop_constraint('Cart_Product_cart_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('Cart_Product_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Product', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Cart', ['cart_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Featured_Product', schema=None) as batch_op:
        batch_op.drop_constraint('Featured_Product_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Product', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Order_Item', schema=None) as batch_op:
        batch_op.drop_constraint('Order_Item_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Order', ['order_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.drop_constraint('Payment_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_constraint('Product_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Category', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('Product_Image', schema=None) as batch_op:
        batch_op.drop_constraint('Product_Image_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Product', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product_Image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Product_Image_product_id_fkey', 'Product', ['product_id'], ['id'])

    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Product_category_id_fkey', 'Category', ['category_id'], ['id'])

    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Payment_user_id_fkey', 'User', ['user_id'], ['id'])

    with op.batch_alter_table('Order_Item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Order_Item_order_id_fkey', 'Order', ['order_id'], ['id'])

    with op.batch_alter_table('Featured_Product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Featured_Product_product_id_fkey', 'Product', ['product_id'], ['id'])

    with op.batch_alter_table('Cart_Product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Cart_Product_product_id_fkey', 'Product', ['product_id'], ['id'])
        batch_op.create_foreign_key('Cart_Product_cart_id_fkey', 'Cart', ['cart_id'], ['id'])

    with op.batch_alter_table('Cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Cart_user_id_fkey', 'User', ['user_id'], ['id'])

    # ### end Alembic commands ###
