"""Changed payment expiry_date data type to Date

Revision ID: 3c836115c178
Revises: 79388c7c94c9
Create Date: 2024-07-13 14:29:21.765655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c836115c178'
down_revision = '79388c7c94c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
