"""User addresses are now automatically deleted when a user is deleted

Revision ID: 5012d92a5b4f
Revises: 8cdc81ea5868
Create Date: 2025-02-06 19:02:50.549822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5012d92a5b4f'
down_revision = '8cdc81ea5868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Address', schema=None) as batch_op:
        batch_op.drop_constraint('Address_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Address_user_id_fkey', 'User', ['user_id'], ['id'])

    # ### end Alembic commands ###
