"""Changed tracking_number to tracking_url and increased character limit

Revision ID: 72e4112e9eef
Revises: 6026b6cc6c52
Create Date: 2025-06-02 21:16:04.527127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e4112e9eef'
down_revision = '6026b6cc6c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_url', sa.String(length=300), nullable=True))
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('tracking_url')

    # ### end Alembic commands ###
