"""Made user email nullable and added created_at attribute

Revision ID: 739e0cc05914
Revises: 8ac2f75fbf1f
Create Date: 2025-02-22 23:05:49.847312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739e0cc05914'
down_revision = '8ac2f75fbf1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # Remove the server default after the column has been populated
    op.alter_column('User', 'created_at', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
