"""Removed address FK from orders table

Revision ID: 8cdc81ea5868
Revises: 93c019855ba5
Create Date: 2025-01-16 01:16:58.321686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdc81ea5868'
down_revision = '93c019855ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_constraint('Order_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Order_address_id_fkey', 'Address', ['address_id'], ['id'])

    # ### end Alembic commands ###
