"""Added stripe attributes to Product

Revision ID: b9f5c77bbaa4
Revises: e9bc787dba47
Create Date: 2025-01-08 20:26:13.110850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f5c77bbaa4'
down_revision = 'e9bc787dba47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')

    # ### end Alembic commands ###
