"""Added is_verified, verification_token and last_verification_email_sent to User. Added tracking_number to Order

Revision ID: ba9e3926cd58
Revises: fd2dbdf43deb
Create Date: 2025-03-04 21:47:19.921356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9e3926cd58'
down_revision = 'fd2dbdf43deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_verification_email_sent', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###

    # Update existing rows to set is_verified to False
    op.execute('UPDATE "User" SET is_verified = FALSE')

    # Remove the server default
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('is_verified', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('last_verification_email_sent')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
