"""Changes to User, Address and Payment information

Revision ID: e9bc787dba47
Revises: a278b8da3157
Create Date: 2024-11-28 17:50:21.706913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bc787dba47'
down_revision = 'a278b8da3157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False, server_default='Default Address Name'))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_id', sa.String(length=50), nullable=False, server_default='Default Payment ID'))
        batch_op.drop_column('card_number')
        batch_op.drop_column('security_code')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('name_on_card')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False, server_default="Default User Name"))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=50), nullable=True))
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # Remove server_default after setting the default values
    op.alter_column('Address', 'full_name', server_default=None)
    op.alter_column('Address', 'is_default', server_default=None)
    op.alter_column('Payment', 'stripe_payment_id', server_default=None)
    op.alter_column('User', 'full_name', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('Payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_on_card', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('security_code', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('card_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('stripe_payment_id')

    with op.batch_alter_table('Address', schema=None) as batch_op:
        batch_op.drop_column('is_default')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
